# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0003_comment_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='restaurant',
        ),
    ]
