# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0004_remove_comment_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
