# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20161027_2051'),
        ('dish_app', '0005_auto_20170213_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='likes',
            field=models.ManyToManyField(related_name='plates', to='login_app.Client'),
        ),
    ]
