# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0007_auto_20170213_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plate',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
    ]
