# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0008_auto_20170214_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='height_field',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plate',
            name='width_field',
            field=models.IntegerField(default=100),
        ),
    ]
