# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0009_auto_20170214_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
